on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production
      deployment: true
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
        
      - name: Update npm
        run: npm install -g npm@11.12.1

      - name: Publish to npm
        run:
          npm publish --provenance
